# coding: utf-8
import numpy as np
import tensorflow as tf
import pandas as pd
import csv
import pickle
import os

def get_eload(path):
    """ Get peak_load data(per hour during the day) from excel files which are generated by SCADA system.
        Get maximum peak load data, Duration : June ~ August, 2011~2017
        Due to occasional communication failiure, some data are missing :
         '12-7-22,'12-7-27, '12-8-27, '17-6-23, '17-6-25, '17-7-22, (inaccurate: '17-8-21, '17-8-22) 
        Manually fixed above data similar to adjacent days """
    
    eload_dic = {}
    load_listdir = os.listdir(path)
    
    for idx, folder in enumerate(load_listdir):
        n_path = path + str(folder)
        n_load_listdir = os.listdir(n_path)
        eload_list = []
        
        for idx2, file in enumerate(n_load_listdir):
            
            final_path = n_path + '/'+ str(file)
            
            # Since names of each file are unorganized, categorize files with respect to the number of sheets.
            if idx < 3:
                day_load = pd.read_excel(final_path, sheet_name=10)
                total_dayload = day_load.loc[3][1:25].tolist()
            
            elif 2 < idx < 18:
                day_load = pd.read_excel(final_path, sheet_name=10)
                total_dayload = day_load.loc[2][1:25].tolist()
                        
            else :
                
                day_load = pd.read_excel(final_path, sheet_name=6)
                total_dayload = day_load.loc[2][1:25].tolist()
                
            eload_list.append(total_dayload)
            if idx2 == 30:
                break
            
        eload_dic[str(folder)] = np.array(eload_list)
            
    return eload_dic

def get_wether(path):
    """Get data(average and maximum, during the day, humidity) from csv file, 
       Duration : from June to August, 2010~2017"""
    file = os.listdir(path)
    weather = {}
    temp_avg = {}
    temp_max = {}
    humid = {}
    for f in file:
        with open(path+str(f)) as ind_file:
            reader = csv.reader(ind_file)
            temper = list(reader)
            
            avg_temp = []
            max_temp = []
            hm = []
            for row in range(len(temper)):
                if row == 0:
                    continue
                else :
                    avg_temp.append(float(temper[row][2]))
                    max_temp.append(float(temper[row][3]))
                    hm.append(float(temper[row][6]))
                    
            weather[str(f)] = np.transpose(np.vstack((np.array(avg_temp), np.array(max_temp), np.array(hm))))
                        
    return  weather


